import React, { useCallback, useEffect, useRef, useState } from "react"
import { FlatList, Pressable, Text, View, useWindowDimensions, type LayoutChangeEvent, type PressableStateCallbackType } from "react-native"
import { Checked, Cross } from "react-native-system-icon"
import { useControllableValue } from "../../hooks"
import { shallowEqualArray, renderTextOrNode } from "../../utils"
import { isFunction, isNumber, isText } from "../../utils/validate"
import Popup from "../popup"
import Tabs from "../tabs"
import type { TabsValue } from "../tabs"
import type { TabsClickEvent } from "../tabs/types"
import { useLocale } from "../config-provider/useLocale"
import { useCascaderTokens } from "./tokens"
import type { CascaderFieldNames, CascaderOption, CascaderProps, CascaderRenderProps, CascaderTokens, CascaderValue } from "./types"
import { useCascaderExtend } from "./useCascaderExtend"
type FieldKeys = { textKey: string; valueKey: string; childrenKey: string }
const getFieldKeys = (fn?: CascaderFieldNames) => ({ textKey: fn?.text ?? "text", valueKey: fn?.value ?? "value", childrenKey: fn?.children ?? "children" })
const resolveRows = (opts: CascaderOption[] = [], k: FieldKeys, vals: CascaderValue[]): CascaderOption[] => { const sel: CascaderOption[] = []; let cur: CascaderOption[] | undefined = opts; vals.forEach(val => { if (!cur?.length) return; const m = cur.find(o => o[k.valueKey] === val); if (m) { sel.push(m); cur = (m[k.childrenKey] as CascaderOption[] | undefined) ?? [] } }); return sel }
const CascaderImpl: React.FC<CascaderProps> = props => {
  const { tokensOverride, options = [], title, placeholder, activeColor, fieldNames, optionRender, showHeader, closeable, closeIcon, onChange, onClose, onFinish, onClickTab, onTabChange, swipeable, style, testID, children, poppable, visible: _v, defaultVisible: _dv, onVisibleChange: _ov, closeOnClickOverlay, closeOnFinish, popupPlacement, popupRound, popupProps, loadingText, ...rest } = props; const locale = useLocale(); const tokens = useCascaderTokens(tokensOverride); const rT = title ?? (locale?.vanCascader?.placeholder ?? tokens.defaults.title); const rP = placeholder ?? (locale?.vanCascader?.placeholder ?? tokens.defaults.placeholder); const rAc = activeColor ?? tokens.colors.tabActive; const rSH = showHeader ?? tokens.defaults.showHeader; const rSw = swipeable ?? tokens.defaults.swipeable; const rPop = poppable ?? tokens.defaults.poppable; const rCO = closeOnClickOverlay ?? tokens.defaults.closeOnClickOverlay; const rCF = closeOnFinish ?? tokens.defaults.closeOnFinish; const rPP = popupPlacement ?? tokens.defaults.popupPlacement; const rPR = popupRound ?? tokens.defaults.popupRound; const rLT = loadingText ?? tokens.defaults.loadingText
  const [value, setValue] = useControllableValue<CascaderValue[]>(props, { defaultValue: [], trigger: "onChange" }); const keys = getFieldKeys(fieldNames); const curVal = Array.isArray(value) ? value : []; const [pending, setPending] = useState<CascaderValue[]>(curVal); const showCl = closeable ?? tokens.defaults.closeable; const [popVis, setPopVis] = useControllableValue<boolean>(props, { defaultValue: false, valuePropName: "visible", defaultValuePropName: "defaultVisible", trigger: "onVisibleChange" }); const cur = rPop ? pending : curVal; const { tabs, items, depth } = useCascaderExtend(options, keys, cur); const { width: winW } = useWindowDimensions(); const [measW, setMeasW] = useState(0); const onTabsLayout = useCallback((e: LayoutChangeEvent) => { const w = e.nativeEvent.layout.width; if (w) setMeasW(prev => prev === w ? prev : w) }, []); const curRows = resolveRows(options, keys, curVal); const [actTab, setActTab] = useState(0)
  useEffect(() => { const len = Array.isArray(cur) ? cur.length : 0; let ti = len; if (ti >= depth) ti = Math.max(depth - 1, 0); setActTab(prev => prev === ti ? prev : ti) }, [cur.length, depth]); useEffect(() => { if (!rPop || !popVis) setPending(prev => (shallowEqualArray(prev, curVal) ? prev : curVal)) }, [curVal, rPop, popVis]); const openPop = useCallback(() => { if (!rPop || popVis) return; setPending(prev => (shallowEqualArray(prev, curVal) ? prev : curVal)); setPopVis(true) }, [curVal, rPop, popVis, setPopVis]); const onCloseRef = useRef(onClose); const onChangeRef = useRef(onChange); const onFinRef = useRef(onFinish); const onClickTabRef = useRef(onClickTab); const onTabChgRef = useRef(onTabChange); onCloseRef.current = onClose; onChangeRef.current = onChange; onFinRef.current = onFinish; onClickTabRef.current = onClickTab; onTabChgRef.current = onTabChange; const closePop = useCallback((notify?: boolean) => { if (!rPop || !popVis) return; setPopVis(false); if (notify) onCloseRef.current?.() }, [rPop, popVis, setPopVis]); const togglePop = useCallback(() => { if (!rPop) return; popVis ? closePop(true) : openPop() }, [closePop, openPop, rPop, popVis]); const isRP = isFunction(children); const rp = isRP ? (children as CascaderRenderProps) : null; const onClkTab = useCallback((e: TabsClickEvent) => { const i = isNumber(e.index) ? e.index : Number(e.name); if (Number.isNaN(i)) return; const tabName = items[i]?.[keys.textKey] as React.ReactNode; onClickTabRef.current?.(i, isText(tabName) ? String(tabName) : rP) }, [items, keys.textKey, rP]); const onTabChg = useCallback((tv: TabsValue, iEx?: number) => { const i = isNumber(iEx) ? iEx : Number(tv); if (Number.isNaN(i)) return; setActTab(i); onTabChgRef.current?.(i) }, []); const onSelect = useCallback((opt: CascaderOption, ti: number) => {
    if (opt.disabled) return; const ov = opt[keys.valueKey]; if (ov == null) return
    const base = (rPop ? pending : curVal).slice(0, ti); const next = [...base, ov as CascaderValue]; const rows = resolveRows(options, keys, next)
    const ch = (opt[keys.childrenKey] as CascaderOption[] | undefined) ?? []; const hasCh = Object.prototype.hasOwnProperty.call(opt, keys.childrenKey); const isAsync = hasCh && !ch.length; const atDepth = next.length >= depth; const isLeaf = !ch.length && !isAsync
    if (rPop) { setPending(next); onChangeRef.current?.(next, rows) } else setValue(next, rows)
    if (isLeaf || atDepth) { if (rPop) { setValue(next, rows); if (rCF) closePop(true) } onFinRef.current?.(next, rows) }
  }, [curVal, rCF, closePop, depth, keys, options, pending, rPop, setValue])
  const getEmpty = useCallback((ti: number) => { if (ti <= 0) return rP; const p = items[ti - 1]; if (!p) return rP; const hasCh = Object.prototype.hasOwnProperty.call(p, keys.childrenKey); if (!hasCh) return rP; const ch = (p[keys.childrenKey] as CascaderOption[] | undefined) ?? []; return ch.length === 0 && cur.length === ti ? rLT : rP }, [cur.length, items, keys.childrenKey, rLT, rP])
  const renderTabs = () => { if (!tabs.length) return <CascaderOptionList optionList={[]} tabIndex={0} selectedValue={cur[0]} activeColor={rAc} keys={keys} optionRender={optionRender} onSelect={onSelect} tokens={tokens} emptyText={getEmpty(0)} />; const swEn = !!rSw; const tabsW = measW || winW || undefined; const tbStyle = { height: tokens.sizing.headerHeight, paddingHorizontal: tokens.spacing.tabNavPaddingHorizontal, paddingVertical: tokens.spacing.tabNavPaddingVertical, backgroundColor: tokens.colors.background }; return <View style={tokens.layout.tabsWrapper} onLayout={onTabsLayout}><Tabs style={tabsW ? { width: tabsW } : undefined} active={actTab} onChange={onTabChg} onClickTab={onClkTab} align="center" swipeable={swEn} swipeThreshold={0} scrollable animated duration={300} color={rAc} lineHeight={tokens.sizing.indicatorHeight} titleActiveColor={tokens.colors.tabText} titleInactiveColor={tokens.colors.tabInactive} tabBarStyle={tbStyle} tabStyle={[tokens.layout.tabsItem, { paddingHorizontal: tokens.spacing.tabPaddingHorizontal }]} titleStyle={[tokens.layout.tabsTitle, { fontSize: tokens.typography.tabsTitleSize }]} contentStyle={!swEn ? tokens.layout.tabsContentStatic : undefined}>{tabs.map((optList, i) => { const sel = items[i]; const lbl = isText(sel?.[keys.textKey] as React.ReactNode) ? String(sel?.[keys.textKey]) : ""; const usePh = !lbl; const titleNode = (_: boolean) => <Text style={[tokens.layout.tabTitleNode, { color: usePh ? tokens.colors.tabInactive : tokens.colors.tabText, fontWeight: usePh ? tokens.typography.tabTitlePlaceholderWeight : tokens.typography.tabTitleWeight }]}>{usePh ? rP : lbl}</Text>; return <Tabs.TabPane key={i} name={i} title={titleNode}><CascaderOptionList optionList={optList} tabIndex={i} selectedValue={cur[i]} activeColor={rAc} keys={keys} optionRender={optionRender} onSelect={onSelect} tokens={tokens} emptyText={getEmpty(i)} /></Tabs.TabPane> })}</Tabs></View> }; const inlineCh = !rPop && !isRP ? children : null
  const content = <View testID={testID} style={[tokens.layout.container, { backgroundColor: tokens.colors.background }, style]} {...rest}>{rSH ? <View style={[tokens.layout.header, { height: tokens.sizing.headerHeight, paddingHorizontal: tokens.spacing.headerPaddingHorizontal }]}>{renderTextOrNode(rT, [tokens.layout.title, { color: tokens.colors.headerText, fontSize: tokens.typography.titleSize, fontWeight: tokens.typography.titleWeight }])}{showCl ? <Pressable hitSlop={8} onPress={() => { rPop ? closePop(true) : onCloseRef.current?.() }} style={[tokens.layout.closeButton, { marginLeft: tokens.spacing.closeButtonMarginLeft }]} accessibilityRole="button" accessibilityLabel={locale?.vanCascader?.close ?? 'Close'}>{closeIcon ?? ((state: PressableStateCallbackType) => <Cross size={tokens.sizing.closeIconSize} fill={state.pressed ? tokens.colors.closeIconActive : tokens.colors.closeIcon} color={state.pressed ? tokens.colors.closeIconActive : tokens.colors.closeIcon} />)}</Pressable> : null}</View> : null}{renderTabs()}{inlineCh ? <View style={[tokens.layout.inlineChildren, { paddingVertical: tokens.spacing.inlineChildrenPaddingVertical, paddingHorizontal: tokens.spacing.headerPaddingHorizontal }]}>{inlineCh}</View> : null}</View>
  if (!rPop) return content
  const { closeOnOverlayPress: ovClose, overlay: popOv, onOpen: popOnOpen, onOpened: popOnOpened, onClose: popOnClose, onClosed: popOnClosed, ...popRest } = popupProps ?? {}
  const popOnCloseRef = useRef(popOnClose); popOnCloseRef.current = popOnClose
  const onPopupClose = useCallback(() => { popOnCloseRef.current?.(); closePop(true) }, [closePop])
  const actions = { open: openPop, close: () => closePop(true), toggle: togglePop }
  const enhanceTrigger = useCallback((node: React.ReactNode) => { if (!React.isValidElement(node)) return node; const p = node.props as { onPress?: () => void; onClick?: () => void }; const onP = () => { p.onPress?.(); p.onClick?.(); openPop() }; return React.cloneElement(node as React.ReactElement<Record<string, unknown>>, { onPress: onP, onClick: onP }) }, [openPop])
  const triggerNode = rp ? rp(curVal, curRows, actions) : (isRP ? null : children || null); const renderTrigger = enhanceTrigger(triggerNode)
  return <>{renderTrigger}<Popup visible={popVis} placement={rPP} round={rPR} closeOnOverlayPress={ovClose ?? rCO} overlay={popOv ?? true} safeAreaInsetTop={popRest?.safeAreaInsetTop != null ? popRest.safeAreaInsetTop : rSH && showCl} safeAreaInsetBottom={popRest?.safeAreaInsetBottom != null ? popRest.safeAreaInsetBottom : rPP === 'bottom'} onOpen={popOnOpen} onOpened={popOnOpened} onClose={onPopupClose} onClosed={popOnClosed} {...popRest} style={{ paddingLeft: 0, paddingRight: 0 }}>{content}</Popup></>
}
const CascaderOptionItem = React.memo(({ option, tabIndex, selected, activeColor, keys, optionRender, onSelect, tokens }: { option: CascaderOption; tabIndex: number; selected: boolean; activeColor: string; keys: FieldKeys; optionRender?: CascaderProps['optionRender']; onSelect: (option: CascaderOption, tabIndex: number) => void; tokens: CascaderTokens }) => {
  const ov = option[keys.valueKey]; const lbl = option[keys.textKey]; const dis = !!option.disabled; const baseCl = option.color ?? tokens.colors.optionText; const txtCl = dis ? tokens.colors.optionDisabled : selected ? option.color ?? activeColor : baseCl; const txtStyle = [tokens.layout.optionText, { color: txtCl, fontSize: tokens.typography.optionTextSize }, selected ? { fontWeight: tokens.typography.optionTextActiveWeight } : null]; const rawCnt = optionRender ? optionRender({ option, selected }) : renderTextOrNode(lbl as React.ReactNode, txtStyle as any); const cnt = isText(rawCnt) ? renderTextOrNode(rawCnt, txtStyle as any) : rawCnt
  return <Pressable testID={`cascader-option-${tabIndex}-${String(ov)}`} style={({ pressed }) => [tokens.layout.option, { minHeight: tokens.sizing.optionMinHeight, paddingVertical: tokens.spacing.optionPaddingVertical, paddingHorizontal: tokens.spacing.optionPaddingHorizontal }, pressed && !dis && { backgroundColor: tokens.colors.optionActiveBackground }]} onPress={() => onSelect(option, tabIndex)} disabled={dis}><View style={tokens.layout.optionContent}><View style={[tokens.layout.optionLabel, { marginRight: tokens.spacing.optionLabelMarginRight }]}>{cnt}</View>{selected ? <Checked size={tokens.sizing.selectedIconSize} fill={activeColor} color={activeColor} /> : null}</View></Pressable>
})
const CascaderOptionList = React.memo(({ optionList, tabIndex, selectedValue, activeColor, keys, optionRender, onSelect, tokens, emptyText }: { optionList: CascaderOption[]; tabIndex: number; selectedValue?: CascaderValue; activeColor: string; keys: FieldKeys; optionRender?: CascaderProps['optionRender']; onSelect: (option: CascaderOption, tabIndex: number) => void; tokens: CascaderTokens; emptyText: string }) => {
  const renderItem = useCallback(({ item }: { item: CascaderOption }) => <CascaderOptionItem option={item} tabIndex={tabIndex} selected={selectedValue === item[keys.valueKey]} activeColor={activeColor} keys={keys} optionRender={optionRender} onSelect={onSelect} tokens={tokens} />, [activeColor, keys, onSelect, optionRender, selectedValue, tabIndex, tokens]); const keyExt = useCallback((item: CascaderOption) => String(item[keys.valueKey]), [keys.valueKey])
  if (!optionList.length) return <View style={[tokens.layout.optionList, { height: tokens.sizing.optionListHeight }]}><Text style={[tokens.layout.empty, { color: tokens.colors.placeholder, paddingVertical: tokens.spacing.emptyPaddingVertical, fontSize: tokens.typography.emptyTextSize }]}>{emptyText}</Text></View>
  return <FlatList data={optionList} style={[tokens.layout.optionList, { height: tokens.sizing.optionListHeight }]} contentContainerStyle={{ paddingTop: tokens.spacing.optionListPaddingTop, paddingBottom: tokens.spacing.optionListPaddingBottom }} showsVerticalScrollIndicator={false} renderItem={renderItem} keyExtractor={keyExt} removeClippedSubviews initialNumToRender={20} windowSize={5} />
})
const Cascader = React.memo(CascaderImpl); export default Cascader
