import React, { useContext, useMemo } from 'react'
import { ActivityIndicator, Platform, Pressable, Text, View } from 'react-native'
import { withAlpha } from '../../utils/color'
import { createPlatformShadow } from '../../utils/createPlatformShadow'
import { createHairlineView } from '../../utils/hairline'
import { ensureSpace } from '../../utils/string'
import { isFiniteNumber, isFunction, isString } from '../../utils'
import { useAriaPress } from '../../hooks'
import type { ButtonProps, ButtonShadowLevel } from './types'
import { ButtonGroupContext } from './ButtonContext'
import { useButtonTokens } from './tokens'

const clampShadowLevel = (level: number): ButtonShadowLevel =>
  level <= 1 ? 1 : level >= 3 ? 3 : level as ButtonShadowLevel

const ROUND_CORNER_STYLE = { overflow: 'hidden' as const }

const ButtonImpl = (props: ButtonProps, forwardedRef: React.ForwardedRef<React.ElementRef<typeof Pressable>>) => {
  const grp = useContext(ButtonGroupContext); const { text, children, icon, iconPosition: iconPosP, type: typeP, size: sizeP, color, textColor: txtClrP, plain: plainP, block: blockP, round: roundP, square: sqP, hairline: hlP, shadow: shP, loading: loadP, loadingText, loadingIndicator, loadingSize: loadSzP, disabled: disP, allowFontScaling: fontScaleP, maxFontSizeMultiplier, rippleColor: rippleP, contentStyle, textStyle, tokensOverride, style, ...pressProps } = props
  const tokens = useButtonTokens(tokensOverride); const type = typeP ?? grp?.type ?? tokens.defaults.type; const size = sizeP ?? grp?.size ?? tokens.defaults.size; const plain = plainP ?? grp?.plain ?? tokens.defaults.plain; const block = blockP ?? grp?.block ?? tokens.defaults.block; const round = roundP ?? grp?.round ?? tokens.defaults.round; const square = sqP ?? grp?.square ?? tokens.defaults.square; const hairline = hlP ?? grp?.hairline ?? tokens.defaults.hairline; const iconPos = iconPosP ?? grp?.iconPosition ?? tokens.defaults.iconPosition; const disabled = disP ?? grp?.disabled ?? tokens.defaults.disabled; const loading = loadP ?? tokens.defaults.loading; const loadSz = loadSzP ?? tokens.defaults.loadingSize; const allowFontScaling = fontScaleP ?? tokens.defaults.allowFontScaling; const shVal = shP ?? grp?.shadow; const isDis = disabled || loading
  const tone = tokens.colors.tones[type] ?? tokens.colors.tones.default; const szTok = tokens.sizing.sizes[size]; const [bgClr, borderClr, txtClr] = useMemo((): [string, string, string] => plain ? [tokens.colors.backgroundPlain, color ?? tone.border, txtClrP ?? (type === 'default' && !color ? tone.text : color ?? tone.border)] : [color ?? tone.background, color ?? tone.border, txtClrP ?? (color ? '#ffffff' : tone.text)], [color, txtClrP, plain, type, tone, tokens.colors.backgroundPlain]); const hasBorder = plain || type === 'default'; const useHl = hasBorder && hairline; const borderW = hasBorder && !hairline ? tokens.borders.width : 0; const radius = square ? 0 : round ? szTok.height / 2 : szTok.radius
  const shStyle = useMemo(() => { if (plain) return undefined; const lvl = isFiniteNumber(shVal) ? clampShadowLevel(shVal) : shVal === true ? 2 as ButtonShadowLevel : undefined; return lvl ? createPlatformShadow(tokens.shadows[lvl]) : undefined }, [shVal, plain, tokens.shadows]); const { onPress, onPressIn, onPressOut, accessibilityLabel, accessibilityHint, accessibilityRole, accessibilityState, android_ripple: andRippleP, ...viewProps } = pressProps; const { interactionProps, states } = useAriaPress({ disabled: isDis, onPress: onPress || undefined, onPressStart: onPressIn || undefined, onPressEnd: onPressOut || undefined }); const opacity = disabled ? tokens.states.disabledOpacity : loading ? tokens.states.loadingOpacity : states.pressed ? tokens.states.pressedOpacity : 1
  const txtStyle = useMemo(() => ({ fontFamily: tokens.typography.fontFamily, fontWeight: tokens.typography.fontWeight, fontSize: szTok.fontSize, lineHeight: szTok.fontSize * tokens.typography.lineHeightMultiplier, color: txtClr }), [tokens.typography, szTok.fontSize, txtClr]); const iconGap = tokens.spacing.iconGap
  const rIcon = () => { if (!icon) return null; try { const el = isFunction(icon) ? icon(txtClr, szTok.iconSize) : icon; const margin = iconPos === 'left' ? { marginRight: iconGap } : { marginLeft: iconGap }; return <View style={[tokens.layout.iconWrapper, margin]}>{el}</View> } catch (err) { if (__DEV__) console.warn('[Button] Failed to render icon:', err); return null } }; const rLoad = () => <View style={[tokens.layout.iconWrapper, { marginRight: iconGap }]}>{loadingIndicator ?? <ActivityIndicator size={loadSz} color={txtClr} />}</View>; const label = loading && loadingText !== undefined ? loadingText : text !== undefined ? text : children
  const rLabel = () => { if (label == null) return null; if (typeof label === 'string' || typeof label === 'number') return <Text style={[tokens.layout.text, txtStyle, textStyle]} numberOfLines={1} allowFontScaling={allowFontScaling} maxFontSizeMultiplier={maxFontSizeMultiplier}>{isString(label) ? ensureSpace(label, true) : String(label)}</Text>; return label }; const accLabel = accessibilityLabel ?? (typeof label === 'string' || typeof label === 'number' ? String(label) : undefined); const accState = useMemo(() => ({ ...accessibilityState, disabled: isDis, busy: loading }), [accessibilityState, isDis, loading]); const andRipple = useMemo(() => { if (Platform.OS !== 'android') return andRippleP; if (andRippleP) return andRippleP; const rc = rippleP ?? (plain ? txtClr : type === 'default' && !color ? withAlpha(txtClr, 0.15) : tokens.colors.ripple); return { color: rc, borderless: false } }, [andRippleP, rippleP, plain, txtClr, type, color, tokens.colors.ripple])
  return <Pressable ref={forwardedRef} disabled={isDis} style={[tokens.layout.base, { minHeight: szTok.height, paddingHorizontal: szTok.paddingHorizontal, borderRadius: radius, backgroundColor: bgClr, borderColor: useHl ? 'transparent' : borderClr, borderWidth: borderW, opacity }, Platform.OS === 'android' && radius > 0 && !shStyle ? ROUND_CORNER_STYLE : null, block ? tokens.layout.block : null, shStyle, style]} android_ripple={andRipple} {...interactionProps} accessibilityState={accState} accessibilityRole={accessibilityRole ?? 'button'} accessibilityLabel={accLabel} accessibilityHint={accessibilityHint} {...viewProps}><View style={[tokens.layout.content, contentStyle]}>{loading ? <>{rLoad()}{rLabel()}</> : <>{icon && iconPos === 'left' && rIcon()}{rLabel()}{icon && iconPos === 'right' && rIcon()}</>}</View>{useHl && <View style={createHairlineView({ position: 'all', color: borderClr, borderRadius: radius })} />}</Pressable>
}
const ButtonForwardRef = React.forwardRef<React.ElementRef<typeof Pressable>, ButtonProps>(ButtonImpl)
export const Button = React.memo(ButtonForwardRef)
export default Button
