import React, { useContext, useEffect, useRef, useState } from 'react'
import { isFunction, isString } from '../../utils/base'
import { FormContext, FORM_ALL_FIELDS_KEY, normalizeTrigger, serializeNamePath } from './Form'
import type { FormItemProps, FormItemRule } from './types'

export type { FormItemProps, FormItemRule } from './types'

const EMPTY_RULES: FormItemRule[] = []
const EMPTY_VALUES: Record<string, unknown> = {}

const FormItemImpl: React.FC<FormItemProps> = ({ name, label, description, intro, tooltip, rules, dependencies, valuePropName = 'value', trigger = 'onChangeText', validateTrigger, showValidateMessage, required, shouldUpdate, initialValue, children }) => {
  const renderProps = typeof children === 'function'; const ctx = useContext(FormContext); const normRules = rules ?? EMPTY_RULES; const nKey = name ? serializeNamePath(name) : undefined; const shouldAlwaysUp = renderProps && !nKey && !shouldUpdate; const prevValsRef = useRef<Record<string, unknown>>(EMPTY_VALUES); const [, forceUpdate] = useState(0)
  useEffect(() => { if (!ctx?.subscribe) return undefined; return ctx.subscribe((ch, all) => { if (FORM_ALL_FIELDS_KEY in ch) { forceUpdate(v => v + 1); return }; if (shouldAlwaysUp) { forceUpdate(v => v + 1); return }; if (shouldUpdate) { if (shouldUpdate(prevValsRef.current, all)) forceUpdate(v => v + 1); return }; if (nKey && nKey in ch) forceUpdate(v => v + 1) }) }, [ctx, nKey, shouldUpdate, shouldAlwaysUp]); const curVals = ctx?.getFieldsValue() ?? EMPTY_VALUES; useEffect(() => { prevValsRef.current = curVals }, [curVals]); useEffect(() => { if (!name || !ctx) return undefined; return ctx.registerField(name, { rules: normRules, dependencies, initialValue, validateTrigger: validateTrigger ?? trigger }) }, [ctx, name, normRules, dependencies, initialValue, validateTrigger, trigger])
  if (!ctx) { if (renderProps) return <>{children({ getFieldValue: () => undefined, getFieldsValue: () => EMPTY_VALUES, form: null })}</>; return <>{children}</> }; const shouldRender = !shouldUpdate || shouldUpdate(prevValsRef.current, curVals); const modelVal = name ? ctx.getFieldValue(name) : undefined; const rShowMsg = showValidateMessage ?? ctx.showValidateMessage ?? true; const fieldErrs = name ? ctx.getFieldError(name) : undefined; const fieldErr = rShowMsg ? fieldErrs?.[0] : undefined; const rRequired = required ?? normRules.some(r => r.required); const rValidateTrigger = normalizeTrigger(validateTrigger ?? trigger)
  if (renderProps) { if (!shouldRender) return null; return <>{children({ getFieldValue: ctx.getFieldValue, getFieldsValue: ctx.getFieldsValue, form: ctx.form || null })}</> }; if (!name) return <>{children}</>; if (!shouldRender) return null; const chArr = React.Children.toArray(children); if (chArr.length !== 1) return <>{children}</>; const child = chArr[0] as React.ReactElement<Record<string, unknown>>; const handleChange = (next: unknown) => { ctx.setFieldValue(name, next, trigger); const orig = (child.props as Record<string, unknown>)[trigger]; if (isFunction(orig)) orig(next) }; const dispName = (child.type as unknown as { displayName?: string }).displayName; const isFieldLike = isString(dispName) && (dispName.includes('Field') || dispName.includes('Input')); const rValue = () => { const cv = (child.props as Record<string, unknown>)[valuePropName]; if (cv !== undefined) return cv; if (modelVal !== undefined) return modelVal; if (isFieldLike && valuePropName === 'value') return ''; return modelVal }; const injected: Record<string, unknown> = { [valuePropName]: rValue(), [trigger]: handleChange }; rValidateTrigger.forEach(ev => { if (!ev || ev === trigger) return; const orig = (child.props as Record<string, unknown>)[ev]; injected[ev] = (...args: unknown[]) => { if (isFunction(orig)) orig(...args); ctx.validateField(name, ev) } }); const cp = child.props; if (label !== undefined && cp.label === undefined) injected.label = label; if (ctx.colon !== undefined && injected.label !== undefined && cp.colon === undefined) injected.colon = ctx.colon; if (ctx.labelWidth !== undefined && cp.labelWidth === undefined) injected.labelWidth = ctx.labelWidth; if (description && cp.description === undefined) injected.description = description; if (intro && cp.intro === undefined) injected.intro = intro; if (tooltip && cp.tooltip === undefined) injected.tooltip = tooltip; if (rRequired && cp.required === undefined) injected.required = true; if (fieldErr && cp.errorMessage === undefined) { injected.error = true; injected.errorMessage = fieldErr }; return React.cloneElement(child, injected)
}

FormItemImpl.displayName = 'FormItem'
export const FormItem = React.memo(FormItemImpl)
export default FormItem
