import React, { useCallback, useMemo } from 'react'
import { View, type LayoutChangeEvent } from 'react-native'
import { createHairlineView } from '../../utils'
import { useGridTokens } from './tokens'
import type { GridDirection, GridProps, GridTokens } from './types'

export interface GridContextValue { columnNum: number; gutter: number; border: boolean; center: boolean; square: boolean; direction: GridDirection; reverse: boolean; clickable: boolean; iconSize: number; iconColor?: string; count: number; containerWidth: number; tokens: GridTokens }
export const GridContext = React.createContext<GridContextValue | null>(null)

const GridImpl: React.FC<GridProps> = props => {
  const { tokensOverride, children, columnNum: colNumP, gutter: gutP, border: borderP, center: centerP, square: sqP, direction: dirP, reverse: revP, clickable: clkP, iconSize: iconSzP, iconColor, style, onLayout: onLayoutProp, ...rest } = props; const tokens = useGridTokens(tokensOverride); const [containerWidth, setContainerWidth] = React.useState(0); const columnNum = useMemo(() => { const v = colNumP ?? tokens.defaults.columnNum; return Number.isFinite(v) && v > 0 ? Math.floor(v) : tokens.defaults.columnNum }, [colNumP, tokens.defaults.columnNum]); const gutter = useMemo(() => { const v = gutP ?? tokens.defaults.gutter; return Number.isFinite(v) && v > 0 ? v : 0 }, [gutP, tokens.defaults.gutter]); const border = borderP ?? tokens.defaults.border; const center = centerP ?? tokens.defaults.center; const square = sqP ?? tokens.defaults.square; const direction = dirP ?? tokens.defaults.direction; const reverse = revP ?? tokens.defaults.reverse; const clickable = clkP ?? tokens.defaults.clickable; const iconSize = useMemo(() => { const v = iconSzP ?? tokens.defaults.iconSize; return Number.isFinite(v) && v > 0 ? v : tokens.defaults.iconSize }, [iconSzP, tokens.defaults.iconSize]); const childrenArray = useMemo(() => React.Children.toArray(children).filter((c): c is React.ReactElement<any> => React.isValidElement(c)), [children]); const showBorder = border && !gutter; const borderClr = tokens.colors.border; const topBorder = useMemo(() => showBorder ? <View style={[tokens.layout.border, tokens.layout.borderTop, createHairlineView({ position: 'top', color: borderClr, left: 0, right: 0, top: 0 })]} /> : null, [borderClr, showBorder, tokens.layout.border, tokens.layout.borderTop]); const bottomBorder = useMemo(() => showBorder ? <View style={[tokens.layout.border, tokens.layout.borderBottom, createHairlineView({ position: 'bottom', color: borderClr, left: 0, right: 0, bottom: 0 })]} /> : null, [borderClr, showBorder, tokens.layout.border, tokens.layout.borderBottom]); const ctxVal = useMemo(() => ({ columnNum, gutter, border, center, square, direction, reverse, clickable, iconSize, iconColor, count: childrenArray.length, containerWidth, tokens }), [border, center, childrenArray.length, clickable, columnNum, containerWidth, direction, gutter, iconColor, iconSize, reverse, square, tokens]); const rendered = useMemo(() => childrenArray.map((child, i) => React.cloneElement(child, { gridItemIndex: i, key: child.key ?? i })), [childrenArray]); const onLayout = useCallback((e: LayoutChangeEvent) => { setContainerWidth(e.nativeEvent.layout.width); onLayoutProp?.(e) }, [onLayoutProp])
  return <GridContext.Provider value={ctxVal}><View accessibilityRole={'grid' as any} onLayout={onLayout} style={[tokens.layout.container, gutter ? { columnGap: gutter, rowGap: gutter } : undefined, style]} {...rest}>{topBorder}{rendered}{bottomBorder}</View></GridContext.Provider>
}
export const Grid = React.memo(GridImpl)
Grid.displayName = 'Grid'
