import React, { useMemo } from 'react'
import { View, type LayoutChangeEvent } from 'react-native'
import { createHairlineView } from '../../utils/hairline'
import { useGridTokens } from './tokens'
import type { GridProps } from './types'

const GridImpl: React.FC<GridProps> = props => {
  const { tokensOverride, children, columnNum: colNumP, gutter: gutP, border: borderP, center: centerP, square: sqP, direction: dirP, reverse: revP, clickable: clkP, iconSize: iconSzP, iconColor, style, onLayout: onLayoutProp, ...rest } = props; const tokens = useGridTokens(tokensOverride); const [containerWidth, setContainerWidth] = React.useState(0); const rawCol = colNumP ?? tokens.defaults.columnNum; const columnNum = Number.isFinite(rawCol) && rawCol > 0 ? Math.floor(rawCol) : tokens.defaults.columnNum; const rawGutter = gutP ?? tokens.defaults.gutter; const gutter = Number.isFinite(rawGutter) && rawGutter > 0 ? rawGutter : 0; const border = borderP ?? tokens.defaults.border; const center = centerP ?? tokens.defaults.center; const square = sqP ?? tokens.defaults.square; const direction = dirP ?? tokens.defaults.direction; const reverse = revP ?? tokens.defaults.reverse; const clickable = clkP ?? tokens.defaults.clickable; const rawIconSize = iconSzP ?? tokens.defaults.iconSize; const iconSize = Number.isFinite(rawIconSize) && rawIconSize > 0 ? rawIconSize : tokens.defaults.iconSize; const childrenArray = useMemo(() => React.Children.toArray(children).filter((c): c is React.ReactElement<any> => React.isValidElement(c)), [children]); const showBorder = border && !gutter; const borderClr = tokens.colors.border; const topBorder = showBorder ? <View style={[tokens.layout.border, tokens.layout.borderTop, createHairlineView({ position: 'top', color: borderClr, left: 0, right: 0, top: 0 })]} /> : null; const bottomBorder = showBorder ? <View style={[tokens.layout.border, tokens.layout.borderBottom, createHairlineView({ position: 'bottom', color: borderClr, left: 0, right: 0, bottom: 0 })]} /> : null; const rendered = useMemo(() => childrenArray.map((child, i) => React.cloneElement(child, { key: child.key ?? i, gridItemIndex: i, gridTokens: tokens, gridColumnNum: columnNum, gridGutter: gutter, gridBorder: border, gridCenter: center, gridSquare: square, gridDirection: direction, gridReverse: reverse, gridClickable: clickable, gridIconSize: iconSize, gridIconColor: iconColor, gridCount: childrenArray.length, gridContainerWidth: containerWidth } as any)), [border, center, childrenArray, clickable, columnNum, containerWidth, direction, gutter, iconColor, iconSize, reverse, square, tokens]); const onLayout = (e: LayoutChangeEvent) => { setContainerWidth(e.nativeEvent.layout.width); onLayoutProp?.(e) }
  return <View accessibilityRole={'grid' as any} onLayout={onLayout} style={[tokens.layout.container, gutter ? { columnGap: gutter, rowGap: gutter } : undefined, style]} {...rest}>{topBorder}{rendered}{bottomBorder}</View>
}
export const Grid = React.memo(GridImpl)
Grid.displayName = 'Grid'
