import React, { useCallback, useMemo } from 'react'
import { Pressable, Text, View, type LayoutChangeEvent } from 'react-native'
import type { SelectorProps, SelectorValue } from './types'
import { useSelectorTokens } from './tokens'
import { useAriaPress, useControllableValue } from '../../hooks'
import { isText } from '../../utils'

const CHECK_MARK = '✓'; const CH = 8; const CW = 10
type SelectorComponent = (<V extends SelectorValue>(props: SelectorProps<V>) => React.ReactElement) & { displayName?: string }
type SelectorOptionItemProps<V extends SelectorValue> = { option: SelectorProps<V>['options'][number]; active: boolean; disabled: boolean; multiple: boolean; showCheckMark: boolean; basis: `${number}%`; containerWidth: number; columns: number; gap: number; tokens: ReturnType<typeof useSelectorTokens>; itemStyle?: SelectorProps<V>['itemStyle']; labelStyle?: SelectorProps<V>['labelStyle']; descriptionStyle?: SelectorProps<V>['descriptionStyle']; onToggle: (option: SelectorProps<V>['options'][number]) => void }

const SelectorOptionItemImpl = <V extends SelectorValue>({ option, active, disabled, multiple, showCheckMark, basis, containerWidth: cw, columns, gap, tokens, itemStyle, labelStyle, descriptionStyle, onToggle }: SelectorOptionItemProps<V>) => {
  const labelContent = option.label; const descriptionContent = option.description; const hasDescription = descriptionContent != null; const accessibilityLabel = isText(labelContent) ? String(labelContent) : String(option.value); const accessibilityHint = isText(descriptionContent) ? String(descriptionContent) : undefined; const { interactionProps, states } = useAriaPress({ disabled, onPress: () => onToggle(option), extraProps: { accessibilityRole: multiple ? 'checkbox' : 'radio', accessibilityLabel, accessibilityHint, accessibilityState: multiple ? { checked: active, disabled } : { selected: active, disabled } } }); const pressableStyle = cw > 0 ? { width: (cw - (columns - 1) * gap) / columns, flexGrow: 0, flexShrink: 0 } : { flexBasis: basis, flexShrink: 1 }
  return <Pressable {...interactionProps} style={[tokens.layout.pressable, pressableStyle]}><View style={[tokens.layout.item, { paddingHorizontal: tokens.spacing.paddingHorizontal, paddingVertical: tokens.spacing.paddingVertical, borderRadius: tokens.radii.item, borderColor: active ? tokens.colors.borderActive : tokens.colors.border, backgroundColor: active ? tokens.colors.backgroundActive : tokens.colors.background, opacity: disabled ? tokens.states.disabledOpacity : 1 }, states.pressed && { opacity: 0.9 }, itemStyle]}>{isText(labelContent) ? <Text style={[tokens.layout.label, { color: active ? tokens.colors.textActive : tokens.colors.text, fontSize: tokens.typography.fontSize, lineHeight: tokens.typography.fontSize * 1.4, fontFamily: tokens.typography.fontFamily, fontWeight: tokens.typography.fontWeight }, labelStyle]}>{labelContent}</Text> : labelContent}{hasDescription ? isText(descriptionContent) ? <Text style={[tokens.layout.description, { marginTop: tokens.spacing.descriptionMarginTop, color: disabled ? tokens.colors.disabledText : tokens.colors.description, fontSize: tokens.typography.descriptionSize, lineHeight: tokens.typography.descriptionSize * 1.4 }, descriptionStyle]}>{descriptionContent}</Text> : <View style={{ marginTop: tokens.spacing.descriptionMarginTop }}>{descriptionContent}</View> : null}{active && showCheckMark ? <><View style={[tokens.layout.checkMarkTriangle, { borderTopWidth: CH, borderBottomWidth: CH, borderLeftWidth: CW, borderRightWidth: CW, borderBottomColor: tokens.colors.check, borderRightColor: tokens.colors.check }]} /><Text style={[tokens.layout.checkMark, { color: tokens.colors.checkForeground }]}>{CHECK_MARK}</Text></> : null}</View></Pressable>
}
const SelectorOptionItemMemo = React.memo(SelectorOptionItemImpl); SelectorOptionItemMemo.displayName = 'SelectorOptionItem'
const SelectorOptionItem = SelectorOptionItemMemo as <V extends SelectorValue>(props: SelectorOptionItemProps<V>) => React.ReactElement

const SelectorImpl = <V extends SelectorValue>(props: SelectorProps<V>) => {
  const { tokensOverride, options, columns: colP, multiple: multP, showCheckMark: showChkP, disabled: disP, onChange, itemStyle, labelStyle, descriptionStyle, style, onLayout: onLayoutProp, ...rest } = props; const tokens = useSelectorTokens(tokensOverride); const [containerWidth, setContainerWidth] = React.useState(0); const columns = colP ?? tokens.defaults.columns ?? 1; const multiple = multP ?? tokens.defaults.multiple; const showCheckMark = showChkP ?? tokens.defaults.showCheckMark; const disabled = Boolean(disP ?? tokens.defaults.disabled); const [value = [], triggerChange] = useControllableValue<V[]>(props, { defaultValue: [] }); const optionsByVal = useMemo(() => { const m = new Map<SelectorValue, (typeof options)[number]>(); for (const o of options) m.set(o.value, o); return m }, [options]); const rCols = Math.max(1, Math.floor(columns)); const basis = `${100 / rCols}%` as `${number}%`; const gap = tokens.spacing.gap; const selectedSet = useMemo(() => new Set(value), [value]); const toggleOption = useCallback((option: (typeof options)[number]) => { if (disabled || option.disabled) return; const active = selectedSet.has(option.value); const nextVal: V[] = multiple ? (active ? value.filter(item => item !== option.value) : [...value, option.value]) : (active ? [] : [option.value]); triggerChange(nextVal, { items: nextVal.map(v => optionsByVal.get(v)).filter(Boolean) as (typeof options)[number][] }) }, [disabled, multiple, optionsByVal, selectedSet, triggerChange, value]); const onLayout = useCallback((e: LayoutChangeEvent) => { setContainerWidth(e.nativeEvent.layout.width); onLayoutProp?.(e) }, [onLayoutProp])
  return <View {...rest} onLayout={onLayout} style={[tokens.layout.container, { columnGap: gap, rowGap: gap }, style]} accessibilityRole={multiple ? undefined : 'radiogroup'}>{options.map(option => <SelectorOptionItem key={String(option.value)} option={option} active={selectedSet.has(option.value)} disabled={disabled || Boolean(option.disabled)} multiple={multiple} showCheckMark={showCheckMark} basis={basis} containerWidth={containerWidth} columns={rCols} gap={gap} tokens={tokens} itemStyle={itemStyle} labelStyle={labelStyle} descriptionStyle={descriptionStyle} onToggle={toggleOption} />)}</View>
}
export const Selector = React.memo(SelectorImpl) as unknown as SelectorComponent
Selector.displayName = 'Selector'
export default Selector
