import React, { useEffect, useMemo, useRef } from 'react'
import { Animated, StyleSheet, View, type ViewStyle } from 'react-native'
import { nativeDriverEnabled } from '../../platform/animation'
import { useReducedMotion } from '../../hooks/animation'
import { isFiniteNumber, isString } from '../../utils/base'
import type { SkeletonProps } from './types'
import { useSkeletonTokens } from './tokens'

const normalize = (value: number | string | undefined, fallback: number | string): number | string => isFiniteNumber(value) ? Math.max(0, value) : isString(value) && value.trim() ? value.trim() : fallback

const resolveSeries = (count: number, input: number | string | Array<number | string> | undefined, fallback: number | string): Array<number | string> => Array.from({ length: count }, (_, idx) => normalize(Array.isArray(input) ? input[idx] : input, fallback))

const SkeletonImpl = (props: SkeletonProps, ref: React.ForwardedRef<View>) => {
  const { tokensOverride, isLoaded, loading: loadP, animate: animP, startColor, speed: speedP, avatar: avP, avatarSize: avSzP, avatarShape: avShapeP, title: titleP, titleWidth: titleWP, row: rowP, rowWidth: rowWP, rowHeight, round: roundP, style, children, ...rest } = props; const tokens = useSkeletonTokens(tokensOverride); const reducedMotion = useReducedMotion(); const loading = loadP ?? (isLoaded != null ? !isLoaded : true); const animate = animP ?? true; const avatar = avP ?? false; const avatarSize = avSzP ?? tokens.defaults.avatarSize; const avatarShape = avShapeP ?? 'round'; const title = titleP ?? false; const titleWidth = titleWP ?? tokens.defaults.titleWidth; const row = rowP ?? tokens.defaults.rowCount; const rowWidth = rowWP ?? tokens.defaults.rowWidth; const round = roundP ?? false; const speed = isFiniteNumber(speedP) ? Math.max(0.01, speedP) : isString(speedP) && Number.isFinite(Number(speedP)) && Number(speedP) > 0 ? Number(speedP) : 1; const duration = Math.max(0, tokens.animation.duration / speed); const blockColor = startColor ?? tokens.colors.block; const rows = isFiniteNumber(row) ? Math.max(0, Math.floor(row)) : 0
  const rowWidths = useMemo(() => { const widths = resolveSeries(rows, rowWidth, tokens.defaults.rowWidth); if (!Array.isArray(rowWidth) && rows > 1 && (props.rowWidth === undefined || (isString(props.rowWidth) && props.rowWidth.trim() === '100%'))) widths[rows - 1] = tokens.defaults.lastRowWidth; return widths }, [props.rowWidth, rowWidth, rows, tokens.defaults.lastRowWidth, tokens.defaults.rowWidth]); const rowHeights = useMemo(() => resolveSeries(rows, rowHeight, tokens.defaults.rowHeight), [rowHeight, rows, tokens.defaults.rowHeight]); const titleHeight = rowHeights[0] ?? tokens.defaults.rowHeight; const rAvSz = normalize(avatarSize, tokens.defaults.avatarSize); const rTitleW = normalize(titleWidth, tokens.defaults.titleWidth); const animated = useRef(new Animated.Value(0)).current
  useEffect(() => { if (!loading || !animate || duration <= 0 || reducedMotion) { animated.setValue(0); return }; const loop = Animated.loop(Animated.sequence([Animated.timing(animated, { toValue: 1, duration: duration / 2, useNativeDriver: nativeDriverEnabled, isInteraction: false }), Animated.timing(animated, { toValue: 0, duration: duration / 2, useNativeDriver: nativeDriverEnabled, isInteraction: false })])); loop.start(); return () => loop.stop() }, [animate, animated, duration, loading, reducedMotion]); const animStyle = useMemo(() => (!loading || !animate ? undefined : ({ opacity: animated.interpolate({ inputRange: [0, 1], outputRange: [tokens.animation.minOpacity, tokens.animation.maxOpacity] }) } as unknown as ViewStyle)), [animate, animated, loading, tokens.animation.maxOpacity, tokens.animation.minOpacity]); const ctrStyles = [S.ctr, { gap: tokens.spacing.containerGap }, style]; const avatarNode = useMemo(() => (!avatar ? null : <Animated.View style={[{ width: rAvSz as ViewStyle['width'], height: rAvSz as ViewStyle['height'], borderRadius: avatarShape === 'round' ? 999 : tokens.radius, backgroundColor: blockColor }, animStyle]} />), [animStyle, avatar, avatarShape, blockColor, rAvSz, tokens.radius]); const titleNode = useMemo(() => (!title ? null : <Animated.View style={[{ width: rTitleW as ViewStyle['width'], height: titleHeight as ViewStyle['height'], backgroundColor: blockColor, borderRadius: round ? tokens.radius : 0 }, animStyle]} />), [animStyle, blockColor, rTitleW, round, title, titleHeight, tokens.radius]); const rowNodes = useMemo(() => (rows <= 0 ? null : <View style={S.rows}>{rowWidths.map((w, i) => <Animated.View key={i} testID={`rv-skeleton-row-${i}`} style={[{ width: w as ViewStyle['width'], height: rowHeights[i] as ViewStyle['height'], marginTop: i === 0 && !title ? 0 : tokens.spacing.rowGap, backgroundColor: blockColor, borderRadius: round ? tokens.radius : 0 }, animStyle]} />)}</View>), [animStyle, blockColor, rowHeights, rowWidths, rows, round, title, tokens.radius, tokens.spacing.rowGap]); if (!loading) return <View ref={ref} style={style} {...rest}>{children}</View>; return <View ref={ref} style={ctrStyles} {...rest}>{avatarNode}<View style={S.cnt}>{titleNode}{rowNodes}</View></View>
}

const S = StyleSheet.create({ ctr: { flexDirection: 'row', alignItems: 'flex-start' }, cnt: { flex: 1 }, rows: { width: '100%' } })
const SkeletonForwardRef = React.forwardRef<View, SkeletonProps>(SkeletonImpl)
SkeletonForwardRef.displayName = 'Skeleton'
const Skeleton = React.memo(SkeletonForwardRef)
export default Skeleton
