export { ConfigProvider } from './ConfigProvider'
export { useLocale } from './loc'
export { useDirection } from './dir'
export { zhCN } from './locale/zh-CN'
export { enUS } from './locale/en-US'
export type { ConfigProviderProps, Direction } from './types'
