import React, { useCallback, useImperativeHandle, useMemo, useRef } from 'react'
import { View } from 'react-native'
import { useCheckboxGroup } from '@react-native-aria/checkbox'
import { useCheckboxGroupState, type CheckboxGroupState } from '@react-stately/checkbox'
import type { CheckboxGroupDirection, CheckboxGroupProps, CheckboxIconRender, CheckboxShape, CheckboxValue } from './types'
import { useCheckboxTokens } from './tokens'
import { isBoolean } from '../../utils'

const serialize = (value: CheckboxValue) => String(value)
type RegistryItem = { value: CheckboxValue; disabled?: boolean }

export interface CheckboxGroupContextValue {
  state: CheckboxGroupState; direction: CheckboxGroupDirection; shape?: CheckboxShape; iconSize?: number; iconRender?: CheckboxIconRender; checkedColor?: string; labelDisabled?: boolean; max?: number; registerValue: (key: string, raw: CheckboxValue, disabled?: boolean) => void; unregisterValue: (key: string) => void
}

export const CheckboxGroupContext = React.createContext<CheckboxGroupContextValue | null>(null)

export const CheckboxGroup = React.forwardRef<{ toggleAll: (options?: boolean | { checked?: boolean; skipDisabled?: boolean }) => void }, CheckboxGroupProps>((props, ref) => {
  const { value, defaultValue, onChange, disabled: disabledProp, direction: directionProp, shape, iconSize, checkedColor, iconRender, labelDisabled, max, gap: gapProp, children, style, tokensOverride, accessibilityLabel, accessibilityHint, ...viewProps } = props; const tokens = useCheckboxTokens(tokensOverride); const disabled = disabledProp ?? tokens.defaults.groupDisabled; const direction = directionProp ?? tokens.defaults.groupDirection; const gap = Math.max(0, gapProp ?? tokens.spacing.groupGap); const registryRef = useRef(new Map<string, RegistryItem>()); const state = useCheckboxGroupState({ value: value?.map(serialize), defaultValue: defaultValue?.map(serialize), onChange: next => { onChange?.(next.map(key => registryRef.current.get(key)?.value ?? key)) }, isDisabled: disabled }); const { groupProps } = useCheckboxGroup({ isDisabled: disabled, 'aria-label': accessibilityLabel, 'aria-describedby': accessibilityHint }, state); const gpr = (groupProps ?? {}) as Record<string, unknown>; const { [' aria-disabled']: __ariaDisabledTypo, ...restGP } = gpr; const rGroupProps = useMemo(() => ({ ...restGP, 'aria-disabled': disabled }), [disabled, restGP]); const registerValue = useCallback((key: string, raw: CheckboxValue, itemDisabled?: boolean) => { registryRef.current.set(key, { value: raw, disabled: itemDisabled }) }, []); const unregisterValue = useCallback((key: string) => { registryRef.current.delete(key) }, []); const chArr = useMemo(() => React.Children.toArray(children).filter(ch => ch != null && !isBoolean(ch)), [children]); const toggleAll = useCallback((options: boolean | { checked?: boolean; skipDisabled?: boolean } = {}) => { const opts = isBoolean(options) ? { checked: options } : options; const { checked: tgt, skipDisabled } = opts; const cur = new Set(state.value ?? []); const nextKeys: string[] = []; registryRef.current.forEach((meta, key) => { const isDis = !!meta.disabled || disabled; if (skipDisabled && isDis) { if (cur.has(key)) nextKeys.push(key); return }; if (tgt === true ? true : tgt === false ? false : !cur.has(key)) nextKeys.push(key) }); state.setValue(nextKeys) }, [disabled, state]); useImperativeHandle(ref, () => ({ toggleAll }), [toggleAll]); const ctxVal = useMemo(() => ({ state, direction, shape, iconSize, iconRender, checkedColor, labelDisabled, max, registerValue, unregisterValue }), [checkedColor, direction, iconRender, iconSize, labelDisabled, max, registerValue, shape, state, unregisterValue]); const ctrStyle = [direction === 'horizontal' ? tokens.layout.groupHorizontal : tokens.layout.groupVertical, { columnGap: direction === 'horizontal' ? gap : undefined, rowGap: gap }, style]; return <CheckboxGroupContext.Provider value={ctxVal}><View {...rGroupProps} {...viewProps} accessibilityLabel={accessibilityLabel} accessibilityHint={accessibilityHint} style={ctrStyle}>{chArr}</View></CheckboxGroupContext.Provider>
})
